name: C/C++ CI

on:
  push:
      branches: [lab_2]
  pull_request:
      branches: [lab_2]

jobs:
  build-lab2-gcc48:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
      run: sudo apt install -y libcppunit-dev
      - name: make lab2
      run: make
      - name: make test
      run: make test